api_version = "2024-01"

[[extensions]]
type = "ui_extension"
name = "age-verification-banner"
handle = "age-verification-banner"

[[extensions.targeting]]
module = "./src/index.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
network_access = true